### ISSUE TITLE
[Epic] Combine catalogd and operator-controller into a monorepo

### ISSUE THREAD

**Issue by OchiengEd** [operator-framework/operator-controller#1335]
Combine OLM v1 components (`catalogd` and `operator-controller`) into a monorepo by importing catalogd `apis` and packages into the operator-controller.

 This will build upon the work done in the [RFC](https://docs.google.com/document/d/1mNzwtxhmZyk7fnkO_4AoCCnRR0qC98dOg5GZSJkI8qY/edit) 

 In summary, the task should be completed in two primary phases:

1. Migration
1. Merging

### Phase 1
- [x] https://github.com/operator-framework/operator-controller/issues/1336
- [x] https://github.com/operator-framework/operator-controller/issues/1337
- [x] https://github.com/operator-framework/operator-controller/issues/1342
- [x] https://github.com/operator-framework/operator-controller/issues/1344
- [x] https://github.com/operator-framework/operator-controller/issues/1514
- [x] https://github.com/operator-framework/operator-controller/issues/1338
- [x] https://github.com/operator-framework/operator-controller/issues/1339
- [x] https://github.com/operator-framework/operator-controller/issues/1636
- [x] https://github.com/operator-framework/operator-controller/issues/1518

The following ones might be blocked by a new release with the Monorepo structure, but we should ensure that we have the required artefacts before doing the release. 

- [x] https://github.com/operator-framework/operator-controller/issues/1604
- [x] https://github.com/operator-framework/operator-controller/issues/1605

**Comment by jsm84** [comment]
Linked this to EET-4412 in Jira.

**Comment by camilamacedo86** [comment]
I am closing this one since we’re excited to share that Operator-Controller v1.2.0-rc2 is now available! :tada:

PS: This is an experimental release candidate, incorporating changes from the monorepo initiative. (More info: [Issue #1335](https://github.com/operator-framework/operator-controller/issues/1335))

:drawing_pin: Release notes:  (for all changes since v1.1.0)
- [v1.2.0-rc2](https://github.com/operator-framework/operator-controller/releases/tag/v1.2.0-rc2)
- [v1.2.0-rc1](https://github.com/operator-framework/operator-controller/releases/tag/v1.2.0-rc1)

:warning: This is a pre-release candidate, so if you encounter any issues, please let us know!

**:raised_hands: Huge thanks to all our contributors for making this happen! :rocket:**
