### ISSUE TITLE
[epic] Switch from rukpak to kapp-controller

### ISSUE THREAD

**Issue by ncdc** [operator-framework/operator-controller#590]
Carvel's kapp-controller does much of what rukpak does, and more.

- ~Add kapp-controller App spec template to FBC so operator authors can define how their content should be applied~
- Create App (instead of BundleDeployment) when reconciling an Extension
- [x] #608
   - convert registry v1 to plain manifests using YTT (supporting registry v1 bundles that specify use of webhooks is out of scope for now)
   - based on conversion, create app cr and apply it on cluster
- [x] #611
   - if this ends up being the same as the work outlined in https://github.com/operator-framework/operator-controller/issues/593, can do it at the same time
- [x] #609
- [ ] #610

**Comment by oceanc80** [comment]
Create App (instead of BundleDeployment) when reconciling an Extension
- [ ] support for registry v1 bundle formats when we switch to App
   - convert registry v1 to plain manifests using YTT (supporting registry v1 bundles that specify use of webhooks is out of scope for now)
   - based on conversion, create app cr and apply it on cluster
- [ ] watch all namespaces (if this ends up being the same as the work outlined in #593, can do it at the same time)
- [ ] add kapp in the makefile setup
- [ ] remove rukpak in the makefile setup
