### ISSUE TITLE
[epic] Add Extension API

### ISSUE THREAD

**Issue by ncdc** [operator-framework/operator-controller#591]
The Extension API should be the API users use to instruct the cluster to install/upgrade/delete an extension/operator. This eventually replaces ClusterExtension to become the only user-facing API for extensions/operators.

This will be a namespace-scoped API.

- [x] #596
- [x] #595 
- [x] #592

Follow-ups from #596 and #598

- [x] https://github.com/operator-framework/operator-controller/issues/630
- [x] https://github.com/operator-framework/operator-controller/issues/631
- [x] https://github.com/operator-framework/operator-controller/issues/632
- [x] https://github.com/operator-framework/operator-controller/issues/633
- [x] https://github.com/operator-framework/operator-controller/issues/634
- [x] https://github.com/operator-framework/operator-controller/issues/635
- [x] https://github.com/operator-framework/operator-controller/issues/636
- [x] https://github.com/operator-framework/operator-controller/issues/637
- [x] https://github.com/operator-framework/operator-controller/issues/638

Follow-ups that likely need refactoring based on Helm direction:

- [x] https://github.com/operator-framework/operator-controller/issues/653
- [x] https://github.com/operator-framework/operator-controller/issues/654
- [x] https://github.com/operator-framework/operator-controller/issues/655
- [x] https://github.com/operator-framework/operator-controller/issues/656

**Comment by LalatenduMohanty** [comment]
We decided to stick with ClusterExtension API and relevant cards from this epic have been completed. Hence marking this as done/closed.
