### ISSUE TITLE
Update the Operator CRD Spec to allow me to specify an operator with a particular packageName

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#62]
**User Story:**
As a cluster admin, I would like an operator CRD to be introduced that allows me to define the operator I would like to install. 
**Why is this important?**
- The Operator API will act as a top-level resource for users installing operators. This viewpoint will significantly improve the users ability to understand the state of a given operator.
- The proposed API introduced in this epic consists of a single field within the spec. This is the minimum API service that enables developers to introduce a workflow that will install an operator from a catalogSource on cluster. This work will eventually be expanded upon so we may realize the goals of OLM v1.

**Acceptance Criteria:**
- A new project is created with Kubebuilder.
- A new operator CRD is created.
- The operator API should allow users to specify the packageName.
- A controller exists that reconciles the operator CR.

**Out of Scope:**
- Results do not need to be deterministic. For example, the package may be fulfilled by an entity within any catalogSource.

**Comment by awgreene** [comment]
Prereqs:
- [ ] Branch main to prototype branch
- [ ] Clear main branch history
- [ ] Initialize project with Kubebuilder
- [ ] Introduce the `operator` CRD and controller. The CRD may have an empty spec.

Action Item:
- [] Introduce the spec.Package field.

**Comment by dmesser** [comment]
This is actually done, right?

**Comment by dtfranz** [comment]
Yes, this should be done as of #69
