### ISSUE TITLE
Operator controller uses deppy to find solutions for existing operator CRs

### ISSUE THREAD

**Issue by awgreene** [operator-framework/operator-controller#63]
**User Story:** As a user, I would like the operator controller to be able to identify if it can install a set of bundles that satisfies the existing operator CRs.

**Why is this important?**
- Deppy is being developed as a framework, which will allow other projects to import Deppy as a library that can be used to identify if a set of entities can satisfy a set of constraints. The Operator Controller will then rely on the Deppy library to decide which operator must be installed on cluster based on:
-- user constraints
-- cluster constraints
-- dependency constraints
-- constraints introduced by operators currently installed
- The initial delivery tracked in this epic will only focus on supporting the following constraints:
-- PackageName Constraints: Allowing users to specify that an entity must be from a particular package
-- GVK Uniqueness Constraints: Allowing users to specify that GVKs introduced to the cluster must be provided by a single entity.
- Multiple operator CRs can introduce multiple PackageName constraints.

**Acceptance Criteria:**
- Deppy should be embedded in the Operator Controller, possibly behind an interface so it can easily be moved to its own standalone service.
- The operator controller can:
-- identify when an operator CR cannot be satisfied.
-- identify solutions when they exist.
- The output from Deppy will provide a list of references to bundles that were selected. These references will then be used by the operator controller to create RukPak `bundleDeployments`. The format of the references needs to be determined as a part of this ticket.

**Comment by oceanc80** [comment]
Assumptions:
- We will cache the catalog sources locally on the Operator Controller side
- We will use registryv1 bundles and the existing CatalogSources

Prereqs:

- [ ] Deppy catalog source adapter server
- [ ] Deppy catalog source adapter client
- [ ] Deppy source implementation of entity source
- [ ] Define global constraints: gvk and package uniqueness constraints (should be covered by https://github.com/operator-framework/deppy/pull/55)
- [ ] Decide whether we want to reconcile all operator resources at once vs. one at a time
- [ ] Define an installed bundle constraint (upgrading is out of scope for now)
- [ ] Pipe constraints into solver to get solution
- [ ] Remove operator scaffolding from Deppy https://github.com/operator-framework/deppy/issues/74
- [ ] Enable Deppy to be imported by other packages https://github.com/operator-framework/deppy/issues/73

Action Items:

- [ ] Constraint generator that interfaces with the operator api (required package constraint)
- [ ] Vendor deppy framework into operator api
