### ISSUE TITLE
[epic] Operator Controller supports safe CRD upgrades

### ISSUE THREAD

**Issue by everettraven** [operator-framework/operator-controller#657]
Since operator-controller is focused on lifecycling Kubernetes extensions, an important part of this is ensuring that when upgrades occur that CRDs are upgraded safely. For more information see [Brief: CRD Upgrade Safety](https://docs.google.com/document/d/1J5LP1l46AcLB2AlGoVXRWvHWA5XeZLkgSnQk8yb5brQ/edit?usp=sharing)

Epic project view: https://github.com/orgs/operator-framework/projects/8/views/32

At a high-level this looks like:
- [ ] Updating [carvel-dev/kapp](https://github.com/carvel-dev/kapp) to add a preflight check for CRD Upgrade Safety (**Note**: While we are no longer continuing to build on the carvel tool suite, we will continue to contribute the more generic CRD validations to the kapp project and re-use/re-purpose that code in operator-controller)
    - Carvel Proposal: https://github.com/carvel-dev/carvel/pull/729/files
        - While the proposal is still being ironed out, changes will be made to https://github.com/everettraven/kapp/tree/feature/crd-upgrade-safety-preflight
    - [x] #661
    - [x] #662
    - [x] #663
    - [x] #664
    - [x] #665
    - [x] #666
    - [x] #667
    - [x] ~~#668~~
    - [x] #669
    - [x] #713 
    - [x] #714
    - [x] #715
    - [x] #797
    - [x] #716
- [x] ~~Updating [carvel-dev/kapp-controller](https://github.com/carvel-dev/kapp-controller) to allow configuration of preflight checks~~ (**Note**: We are no longer doing this as we are no longer building on top of the carvel tool suite)
    -  Based on https://github.com/carvel-dev/kapp-controller/issues/1381#issuecomment-1957478793 - this should be a straightforward change once kapp-controller is updated to use a version of kapp that has the preflight check functionality (i believe this bump is done automatically when a new release of kapp is created. see: https://github.com/carvel-dev/kapp-controller/commit/6911c804bd7a6cc0c72b4730339eaa4d0279d795)
    - [x] ~~#688~~
- [ ] Updating operator-controller to run CRD upgrade safety validation
    - [x] #658
    - [x] ~~#660~~
    - [x] ~~#659~~
    - [x] #741 (merge in rukpak first)
    - [x] #742 (merge in rukpak first)
    - [x] #745 (replicate in rukpak first)
    - [x] #877
    
- [x] Documentation: #746

**Comment by everettraven** [comment]
All items in this task list are completed. Closing this issue.
