### ISSUE TITLE
Meta: Helm Integration follow ups

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/operator-controller#903]
This issue tracks the follow ups which are in queue after the helm integration feature is merged to main: #846 

Codebase:

- [x] Limit the number of unpack re-tries in the reconciler: https://github.com/operator-framework/operator-controller/issues/882
- [x] Bump rukpak version to use direct image registry client, instead of spinning up an unpack pod - #853 (https://github.com/operator-framework/operator-controller/pull/905)
- [x] Modify reconciler to use sets pkg from sig-apimachinery while watching dynamic clients: https://github.com/operator-framework/operator-controller/issues/881
- [x] Remove handler implementation from Operator-controller, instead use the one from rukpak: https://github.com/operator-framework/operator-controller/issues/867
- [x] Address error types in reconciler returns: https://github.com/operator-framework/operator-controller/pull/878
- [x] Review and remove the use of rukpak API types: https://github.com/operator-framework/operator-controller/issues/896
- [x] Remove annotations, add APIs for certificates #921 
- [x] Fix: finalizers not set on ClusterExtension #942 
- [x] #869

Tests:
- [x] Modify reconciler to mock `GetInstalledBundle`: https://github.com/operator-framework/operator-controller/pull/899
- [x] Add unit tests in the reconciler for steps after unpack: #879

Moved to #733
- Evaluate the use of Operator conditions in the reconciler: #893

**Comment by joelanford** [comment]
Another thing I just found. We setup finalizers in `main.go`, but then don't actually set them on the reconciler or call `Finalize` during reconciliation. I tried updating to do these things, but then the controller started panic-ing because the finalizer expects to finalize a BundleDeployment, but we are now trying to finalize a ClusterExtension.

**Comment by tmshort** [comment]
@joelanford should this be considered an epic, in place of or addition to #733?
