### ISSUE TITLE
[epic] v1.0.0 Proposed release blockers

### ISSUE THREAD

**Issue by joelanford** [operator-framework/operator-controller#950]
# Approved Release Blockers

# Proposed Release Blockers

# Non-blockers

- [x] #1307

# Resolved
- [x] #1296 
- [x] https://github.com/operator-framework/catalogd/issues/426
- [x] https://github.com/operator-framework/operator-controller/issues/1239
- [x] https://github.com/operator-framework/operator-controller/issues/945
- [x] https://github.com/operator-framework/operator-controller/issues/955
- [x] #879  
- [x] https://github.com/operator-framework/operator-controller/issues/944
- [x] https://github.com/operator-framework/operator-controller/issues/1091
- [x] https://github.com/operator-framework/operator-controller/issues/1109
    - [x] https://github.com/operator-framework/operator-controller/issues/1025 (optimization) - associated with above issue
- [x] https://github.com/operator-framework/operator-controller/issues/1251
- [x] https://github.com/operator-framework/catalogd/issues/392
- [x] https://github.com/operator-framework/operator-controller/issues/961
- [x] https://github.com/operator-framework/operator-controller/issues/914
- [x] #893 
- [x] #1009 
- [x] https://github.com/operator-framework/operator-controller/pull/970
- [x] https://github.com/operator-framework/operator-controller/issues/921
- [x] https://github.com/operator-framework/catalogd/issues/288
- [x] https://github.com/operator-framework/operator-controller/issues/967
- [x] #869 
- [x] https://github.com/operator-framework/operator-controller/issues/994
- [x] https://github.com/operator-framework/operator-controller/issues/983
- [x] https://github.com/operator-framework/operator-controller/issues/987
- [x] https://github.com/operator-framework/operator-controller/issues/923

**Comment by joelanford** [comment]
I took the liberty of moving a few of the release blockers to non-release blockers:
1. #945 is an e2e test. There is no indication today that the actual behavior related to reconciling ClusterExtensions due to ClusterCatalog changes is incorrect.
2. #955 does not change end-user facing APIs for functionality. It can be fixed after 1.0.0.
3. #914 is a performance and UX issue, not an API or functionality change, so we can technically wait until after 1.0.0 to fix it. But I also still think that going out with this as a known issue would be a signal to users that we are unnecessarily rushing 1.0.0.

**Comment by tmshort** [comment]
Added https://github.com/operator-framework/operator-controller/issues/987 as a proposed release blocker (but this can be changed)

**Comment by tmshort** [comment]
And added #970 as a proposed release blocker.

**Comment by joelanford** [comment]
I don't think #869 is a release blocker because it is not a functional or API change. It is an optimization for reducing disk read/write/usage.

**Comment by everettraven** [comment]
@joelanford Just a heads up that I removed #1088 from this epic to be tracked in the v1 API review epic
